### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by unikzforce** [cloudfoundry/winc#7]
Hey there Guys, Is this project alive?
and if not would you please tell me why you decided to abandon it?

**Comment by aemengo** [comment]
This project has not been abandoned. It contains source code for windows components typically used in [cf-deployment](https://github.com/cloudfoundry/cf-deployment). Although commits have slowed down, this project is still being maintained.

Is there a specific issue or question that you have that was not addressed?

**Comment by unikzforce** [comment]
Good to hear that Sir, Thanks a lot.
